
monolith_module.texter.api:
    path: /
    methods: 'GET'
    defaults:
        _controller: TexterModuleBundle:ApiTexter:json

monolith_module.texter.api_html:
    path: /html
    methods: 'GET'
    defaults:
        _controller: TexterModuleBundle:ApiTexter:html

monolith_module.texter.api_html_w_slash:
    path: /html/
    methods: 'GET'
    defaults:
        _controller: TexterModuleBundle:ApiTexter:html
